@echo off
echo Compiling amx_transfer.sma ...
IF EXIST compiled\amx_transfer.amxx DEL compiled\amx_transfer.amxx
amxxpc.exe amx_transfer.sma -d1 -ocompiled/amx_transfer.amxx
echo Coying files ...
IF EXIST compiled/amx_transfer.amxx COPY /Y compiled\amx_transfer.amxx ..\plugins\
echo Done ...
pause
